spring:
  datasource:
    url: jdbc:mysql://localhost:13311/esdb?useSSL=false&allowPublicKeyRetrieval=true
    username: esadmin
    password: esadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
